<MenuScreen>:
    Label: 
        text: 'Menu'

    BoxLayout:
        size_hint_y: None
        height: "48dp"
        spacing: "2dp"
        padding: "2dp"
                
        Button:
            text: 'Articles'
            on_press: root.manager.current = 'articles'
        Button:
            text: 'Analytics'
            on_press: root.manager.current = 'analytics'
        Button:
            text: 'Menu'
            background_color: 0, 1, 1, 1
        Button:
            text: 'Rewards'
            on_press: root.manager.current = 'rewards'
        Button:
            text: 'Slot machine' 
            on_press: root.manager.current = 'slotmachine' 
            
    BoxLayout:
        size_hint_y: None
        height: "48dp"
        top: root.top
        spacing: "2dp"
        padding: "2dp"
               
        
        
        
                                  
<ArticlesScreen>:
    Label: 
        text: 'Articles'

    BoxLayout:
        size_hint_y: None
        height: "48dp"
        spacing: "2dp"
        padding: "2dp"
                
        Button:
            text: 'Articles'
            on_press: root.manager.current = 'articles'
            background_color: 0, 1, 1, 1
        Button:
            text: 'Analytics'
            on_press: root.manager.current = 'analytics'
        Button:
            text: 'Menu'
            on_press: root.manager.current = 'menu'
        Button:
            text: 'Rewards'
            on_press: root.manager.current = 'rewards'
        Button:
            text: 'Slot machine' 
            on_press: root.manager.current = 'slotmachine' 
            
    BoxLayout:
        size_hint_y: None
        height: "48dp"
        top: root.top
        spacing: "2dp"
        padding: "2dp"
            
            
            
            
            
<AnalyticsScreen>:
    Label: 
        text: 'Analytics'

    BoxLayout:
        size_hint_y: None
        height: "48dp"
        spacing: "2dp"
        padding: "2dp"
                
        Button:
            text: 'Articles'
            on_press: root.manager.current = 'articles'
        Button:
            text: 'Analytics'
            on_press: root.manager.current = 'analytics'
            background_color: 0, 1, 1, 1
        Button:
            text: 'Menu'
            on_press: root.manager.current = 'menu'
        Button:
            text: 'Rewards'
            on_press: root.manager.current = 'rewards'
        Button:
            text: 'Slot machine' 
            on_press: root.manager.current = 'slotmachine' 
            
    BoxLayout:
        size_hint_y: None
        height: "48dp"
        top: root.top
        spacing: "2dp"
        padding: "2dp" 





<RewardsScreen>:
    Label: 
        text: 'Rewards'

    BoxLayout:
        size_hint_y: None
        height: "48dp"
        spacing: "2dp"
        padding: "2dp"
                
        Button:
            text: 'Articles'
            on_press: root.manager.current = 'articles'
        Button:
            text: 'Analytics'
            on_press: root.manager.current = 'analytics'
        Button:
            text: 'Menu'
            on_press: root.manager.current = 'menu'
        Button:
            text: 'Rewards'
            on_press: root.manager.current = 'rewards'
            background_color: 0, 1, 1, 1
        Button:
            text: 'Slot machine' 
            on_press: root.manager.current = 'slotmachine' 
            
    BoxLayout:
        size_hint_y: None
        height: "48dp"
        top: root.top
        spacing: "2dp"
        padding: "2dp"            
 
 
 
 
 
<SlotmachineScreen>:
    Label: 
        text: 'Slot machine'

    BoxLayout:
        size_hint_y: None
        height: "48dp"
        spacing: "2dp"
        padding: "2dp"
                
        Button:
            text: 'Articles'
            on_press: root.manager.current = 'articles'
        Button:
            text: 'Analytics'
            on_press: root.manager.current = 'analytics'
        Button:
            text: 'Menu'
            on_press: root.manager.current = 'menu'
        Button:
            text: 'Rewards'
            on_press: root.manager.current = 'rewards'
        Button:
            text: 'Slot machine' 
            background_color: 0, 1, 1, 1
            
    BoxLayout:
        size_hint_y: None
        height: "48dp"
        top: root.top
        spacing: "2dp"
        padding: "2dp"

